# workflow name
name: Deploy To Github Pages

# 当有 push 到仓库和外部触发的时候就运行
on: [push, repository_dispatch]

# ACCESS_TOKEN
jobs:
  deploy: 
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest 
    env:
      TZ: Asia/Shanghai    

    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout 🛎️
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
        submodules: true

    # from: https://github.com/actions/setup-node  
    - name: Setup Node.js 10.x 🔧
      uses: actions/setup-node@master
      with:
        node-version: "10.x"

    - name: Install pandoc 🔧
      run: |
        curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | grep "browser_download_url.*deb" | cut -d '"' -f 4 | wget -qi -
        sudo dpkg -i *.deb
        
    - name: Setup Hexo Dependencies 🔧
      run: |
        npm install hexo-cli -g
        npm install
        npm run build

    # from https://github.com/marketplace/actions/deploy-to-github-pages   
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: public # The folder the action should deploy.
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}